[workspace]
members = [
    "sfrl_core",
    "sfrl_engines",
    "sfrl_envs",
    "sfrl_runner",
]
resolver = "2"

[workspace.dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
log = "0.4.28"
burn = "0.19.1"
